config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application#index'
  resources :storys do
    resources :comments, only: [:create]
    resources :new, only: [:index, :new]
    member do
      delete :destroy
      patch :update
    end
  end
  resources :categorys , only: [:index, :show] do
    member do
      get :newest
      get :oldest
      get :popular
    end
  end

  resources :storys, only: [:edit, :update, :new, :create]
  resources :latest, only: [:index, :show]
  resources :legend, only: [:index, :show]
  resources :likes,  only: [:create, :destroy]
  resources :users,  only: [:show]
  get '/storys_detail/:id' => 'storys#show__detail', as: 'show__detail'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :stories
end

app/models/comment.rb
class Comment < ApplicationRecord
belongs_to :user
belongs_to :story
validates :text, presence: true

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :story, counter_cache: :likes_count
  belongs_to :user
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :likes, dependent: :destroy
  has_many :comments
  scope :by_created_at, -> { order('created_at DESC') }
  scope :love, -> { where(Category_id: 1) }
  scope :marriage, -> { where(Category_id: 2) }
  scope :study, -> { where(Category_id: 3) }
  scope :job, -> { where(Category_id: 4) }
  scope :newlife, -> { where(Category_id: 5) }
  scope :travel, -> { where(Category_id: 6) }
  scope :sick, -> { where(Category_id: 7) }
  scope :everydaylife, -> { where(Category_id: 8) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :stories
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :stories
  has_many :comments
  has_many :likes, dependent: :destroy
  has_many :like_stories, through: :likes, source: :story
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  TOP_STORIES_COUNT = 4
  TOP_CATEGORYSTORYS_COUNT = 3

  def index
    @storys = Story.page(params[:page]).per(TOP_STORIES_COUNT).by_created_at
    @categorys = Category.all
    @loves = Story.love.limit(TOP_CATEGORYSTORYS_COUNT)
    @marriages = Story.marriage.limit(TOP_CATEGORYSTORYS_COUNT)
    @studies = Story.study.limit(TOP_CATEGORYSTORYS_COUNT)
    @jobs = Story.job.limit(TOP_CATEGORYSTORYS_COUNT)
    @newlifes = Story.newlife.limit(TOP_CATEGORYSTORYS_COUNT)
    @travels = Story.travel.limit(TOP_CATEGORYSTORYS_COUNT)
    @sicks = Story.sick.limit(TOP_CATEGORYSTORYS_COUNT)
    @everydaylifes = Story.everydaylife.limit(TOP_CATEGORYSTORYS_COUNT)
  end

	before_action :configure_permitted_parameters, if: :devise_controller?

	def configure_permitted_parameters
	  devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
	end
end

app/controllers/categorys_controller.rb
class CategorysController < ApplicationController

  CATEGORY_STORIES_COUNT = 12

  before_action :set_category, only: [:index, :show, :newest, :oldest, :popular]
  before_action :set_sort, only: [:index, :show, :newest]

  def oldest
    @storys = Story.where(category_id: params[:id]).page(params[:page]).per(CATEGORY_STORIES_COUNT).order('created_at ASC')
  end

  def popular
    @storys = Story.where(category_id: params[:id]).page(params[:page]).per(CATEGORY_STORIES_COUNT).order('likes_count DESC')
  end

  private

    def set_category
      @categorys = Category.all
      @category = Category.find(params[:id])
    end

    def set_sort
      @storys = Story.where(category_id: params[:id]).page(params[:page]).per(CATEGORY_STORIES_COUNT).order('created_at DESC')
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = current_user.comments.build(comment_params)
    if @comment.save
      redirect_to story_path(params[:story_id])
    else
      render :index
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(story_id: params[:story_id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

PROFILESTORYS = 6

  def index
    @categorys = Category.all
    @story = Story.new
    @storys = Story.page(params[:page]).per(PROFILESTORYS).by_created_at
  end
end

app/controllers/latest_controller.rb
class LatestController < ApplicationController
  LATESTSTORYS = 12

  def index
    @user = User.find(current_user.id)
    @categorys = Category.all
    @storys = Story.all.page(params[:page]).per(LATESTSTORYS).order('created_at DESC')
  end
end

app/controllers/legend_controller.rb
class LegendController < ApplicationController
  LEGENDSTORYS = 12

# まだ未実装の機能のため、この形で一時保存しています。

  def index
    @user = User.find(current_user.id)
    @story = Story.new
    @storys = Story.all.page(params[:page]).per(LEGENDSTORYS).order('created_at DESC')
    @categorys = Category.all
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_variables


  def create
    like = current_user.likes.create(story_id: @story.id)
  end

  def destroy
    like = Like.where(story_id: @story.id, user_id: current_user.id)
    like.destroy(like.ids)
  end

  private

  def set_variables
    if params[:format]
      @story = Story.find(params[:format])
    else
      @story = Story.find(params[:id])
    end
    @id_name = "#like-link-#{@story.id}"
  end

end

app/controllers/storys_controller.rb
class StorysController < ApplicationController

  before_action :move_to_index, except: :index
  before_action :set_story, only: %i(show show__detail edit destroy update)
  before_action :set_category, only: %i(index new create show show__detail)
  CURRENTSTORYS = 1

  def index
    @storys = Story.all.page(params[:page]).per(CURRENTSTORYS).order('created_at DESC')
  end


  def show
    @comments = @story.comments.includes(:user)
    @comment = Comment.new
  end

  def new
    @story = current_user.stories.build
    @storys = Story.where(user_id: current_user.id)
  end

  def create
    @story = current_user.stories.build(story_params)
    @story.save
  end

  def destroy
    @story.destroy
  end

  def edit
  end

  def update
    @story.update(story_params)
  end

  private
  def set_category
    @categorys = Category.all
  end

  def story_params
    params.require(:story).permit(:title, :category_id, :text)
  end

  def move_to_index
    redirect_to root_url unless user_signed_in?
  end

  def set_story
    @story = Story.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

PROFILESTORYS = 6

  def show
  	@categorys = Category.all
    user = User.find(params[:id])
    @nickname = current_user.name
    @storys = Story.where(user_id: current_user.id).page(params[:page]).per(PROFILESTORYS).by_created_at
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/application/_advertisement.html.erb
<div class="ad">
  <script type="text/javascript">
    var a=[];
    a[0]="https://static.techacademy.jp/magazine/wp-content/uploads/2018/02/online-bootcamp_300-250-3.jpg";
    a[1]="https://static.techacademy.jp/magazine/wp-content/uploads/2016/06/common_01_300-250.jpg";
    a[2]="https://static.techacademy.jp/magazine/wp-content/uploads/2018/07/online-bootcamp_300-250.jpg";
    a[3]="https://s0.2mdn.net/8018237/1-Designer_300x250.jpg";

    var x;
    x=Math.floor(Math.random()*3);

    document.write
      ("<img src='"+a[x]+"'>");
  </script>
</div>

app/views/application/_category.html.erb
<div category_name="恋愛" category_slug="love" data-is="pages-index-bottom-category">
  <div class="story__container">
    <h1>恋愛のストーリー</h1>
    <div class="story-list clearfix">
       <%= render 'application/love_story-box' %>
    </div>
      <%= link_to "恋愛のストーリー一覧", category_path(@categorys.ids[0]), class: "catebtn" %>
  </div>
</div>
<div category_name="結婚" category_slug="marriage" data-is="pages-index-bottom-category">
  <div class="story__container">
    <h1>結婚のストーリー</h1>
    <div class="story-list clearfix">
       <%= render 'application/marriage_story-box' %>
    </div>
      <%= link_to "結婚のストーリー一覧", category_path(@categorys.ids[1]), class: "catebtn" %>
  </div>
</div>
<div category_name="勉強" category_slug="study" data-is="pages-index-bottom-category">
  <div class="story__container">
    <h1>勉強のストーリー</h1>
    <div class="story-list clearfix">
       <%= render 'application/study_story-box' %>
    </div>
      <%= link_to "勉強のストーリー一覧", category_path(@categorys.ids[2]), class: "catebtn" %>
  </div>
</div>
<div category_name="仕事" data-is="pages-index-bottom-category">
  <div class="story__container">
    <h1>仕事のストーリー</h1>
    <div class="story-list clearfix">
       <%= render 'application/job_story-box' %>
    </div>
      <%= link_to "仕事のストーリー一覧", category_path(@categorys.ids[3]), class: "catebtn" %>
  </div>
</div>
<div category_name="新生活" data-is="pages-index-bottom-category">
  <div class="story__container">
    <h1>新生活のストーリー</h1>
    <div class="story-list clearfix">
       <%= render 'application/newlife_story-box' %>
    </div>
      <%= link_to "新生活のストーリー一覧", category_path(@categorys.ids[4]), class: "catebtn" %>
  </div>
</div>
<div category_name="旅行" data-is="pages-index-bottom-category">
  <div class="story__container">
    <h1>旅行のストーリー</h1>
    <div class="story-list clearfix">
       <%= render 'application/travel_story-box' %>
    </div>
      <%= link_to "旅行のストーリー一覧", category_path(@categorys.ids[5]), class: "catebtn" %>
  </div>
</div>
<div category_name="病気" data-is="pages-index-bottom-category">
  <div class="story__container">
    <h1>病気のストーリー</h1>
    <div class="story-list clearfix">
       <%= render 'application/sick_story-box' %>
    </div>
      <%= link_to "病気のストーリー一覧", category_path(@categorys.ids[6]), class: "catebtn" %>
  </div>
</div>
<div category_name="日常生活" data-is="pages-index-bottom-category">
  <div class="story__container">
    <h1>日常生活のストーリー</h1>
    <div class="story-list clearfix">
       <%= render 'application/everydaylife_story-box' %>
    </div>
      <%= link_to "日常生活のストーリー一覧", category_path(@categorys.ids[7]), class: "catebtn" %>
  </div>
</div>

app/views/application/_titlebar.html.erb
<div class="topbarwrapper">
  <div data-is="titlebar-wrapper">
    <div class="titlebar">
      <div class="titlebar-container">
        <div class="leftside">
          <div class="header-search">
            <form>
              <div class="search-wrapper">
                <button class="search-btn" type="submit">
                  <i class="fa fa-search"></i>
                </button>
                <input class="input-search" type="text" name="q" placeholder="ストーリーを検索...">
              </div>
            </form>
          </div>
        </div>
        <a class="logo" href="/">
          <%= image_tag "https://storys.jp/images/layouts/logo-white.png", class: "logo-image", alt: "storys.jp" %>
        </a>
        <div class="right">
          <div class="header-menu">
            <div class="inner clearfix">
              <div class="dropdown">
                <% if user_signed_in? %>
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
                    <% else %>
                  <%= link_to "ログイン", new_user_session_path, class: 'post' %>
                  <%= link_to "新規登録", new_user_registration_path, class: 'post' %>
                <% end %>
              </div>
                <% if user_signed_in? %>
                <%= link_to "#{current_user.name}", user_path(current_user.id), class: "name"%>
                <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div data-is="categorybar-wrapper">
    <div class="categorybar">
      <div class="category-container">
        <div class="menu">
          <a class=" category__bg__after top" href="/"><span data-is="print" label="TOP">TOP</span></a>
          <a class=" category__bg__after latest" href="/latest"><span data-is="print" label="新着">新着</span></a>
          <a class=" category__bg__after legend" href="/legend"><span data-is="print" label="殿堂入り">殿堂入り</span></a>
          <% @categorys.each do |category| %>
            <%= link_to category.name, category_path(category), class:"category__bg__after categories" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/categorys/newest.html.erb
<%= render 'application/titlebar' %>
<div class="container-latest">
  <%= render 'application/toolbar' %>
  <div class="main">
    <div class="category-bar" id="category-wall">
      <div class="bar">
        <img src="<%= @category.image %>" alt="<%= @category.name %>">
        <p><%= @category.name %></p>
      </div>
    </div>
    <div class="main-contents">
      <div class="contents-container clearfix">
        <div class="layout-column-main">
          <div class="order-main">
            <div class="order-menus">
                <span data-is="raw" content="人気">
                  <%= link_to "人気", popular_category_path(@category) %>
                </span>
                <span class="active" data-is="raw" content="新着">
                  <%= link_to '新着', newest_category_path(@category) %>
                </span>
                <span data-is="raw" content="昔の投稿">
                  <%= link_to '昔の投稿', oldest_category_path(@category) %>
                </span>
            </div>
          </div>
          <div class="story-list clearfix">
            <%= render partial: "application/story-box", collection: @storys, as:"story" %>
          </div>
          <div data-is="category__paginate">
            <%= paginate(@storys) %>
          </div>
          <%= render 'layouts/recommend' %>
        </div>
          <div class="all-count">
            全 <span> 000 </span> ストーリー
          </div>
          <%= render 'latest/rightside' %>
        </div>
    </div>
    <%= render 'application/footer' %>
  </div>
</div>

app/views/categorys/oldest.html.erb
<%= render 'application/titlebar' %>
<div class="container-latest">
  <%= render 'application/toolbar' %>
  <div class="main">
    <div class="category-bar" id="category-wall">
      <div class="bar">
        <img src="<%= @category.image %>" alt="<%= @category.name %>">
        <p><%= @category.name %></p>
      </div>
    </div>
    <div class="main-contents">
      <div class="contents-container clearfix">
        <div class="layout-column-main">
          <div class="order-main">
            <div class="order-menus">
                <span data-is="raw" content="人気">
                  <%= link_to "人気", popular_category_path(@category) %>
                </span>
                <span data-is="raw" content="新着">
                  <%= link_to '新着', newest_category_path(@category) %>
                </span>
                <span class="active" data-is="raw" content="昔の投稿">
                  <%= link_to '昔の投稿', oldest_category_path(@category) %>
                </span>
            </div>
          </div>
          <div class="story-list clearfix">
            <%= render partial: "application/story-box", collection: @storys, as:"story" %>
          </div>
          <div data-is="category__paginate">
            <%= paginate(@storys) %>
          </div>
          <%= render 'layouts/recommend' %>
        </div>
          <div class="all-count">
            全 <span> 000 </span> ストーリー
          </div>
          <%= render 'latest/rightside' %>
        </div>
    </div>
    <%= render 'application/footer' %>
  </div>
</div>

app/views/categorys/popular.html.erb
<%= render 'application/titlebar' %>
<div class="container-latest">
  <%= render 'application/toolbar' %>
  <div class="main">
    <div class="category-bar" id="category-wall">
      <div class="bar">
        <img src="<%= @category.image %>" alt="<%= @category.name %>">
        <p><%= @category.name %></p>
      </div>
    </div>
    <div class="main-contents">
      <div class="contents-container clearfix">
        <div class="layout-column-main">
          <div class="order-main">
            <div class="order-menus">
                <span class="active" data-is="raw" content="人気">
                  <%= link_to "人気", popular_category_path(@category) %>
                </span>
                <span data-is="raw" content="新着">
                  <%= link_to '新着', newest_category_path(@category) %>
                </span>
                <span data-is="raw" content="昔の投稿">
                  <%= link_to '昔の投稿', oldest_category_path(@category) %>
                </span>
            </div>
          </div>
          <div class="story-list clearfix">
            <%= render partial: "application/story-box", collection: @storys, as:"story" %>
          </div>
          <div data-is="category__paginate">
            <%= paginate(@storys) %>
          </div>
          <%= render 'layouts/recommend' %>
        </div>
          <div class="all-count">
            全 <span> 000 </span> ストーリー
          </div>
          <%= render 'latest/rightside' %>
        </div>
    </div>
    <%= render 'application/footer' %>
  </div>
</div>

app/views/categorys/show.html.erb
<%= render 'application/titlebar' %>
<div class="container-latest">
  <%= render 'application/toolbar' %>
  <div class="main">
    <div class="category-bar" id="category-wall">
      <div class="bar">
        <img src="<%= @category.image %>" alt="<%= @category.name %>">
        <p><%= @category.name %></p>
      </div>
    </div>
    <div class="main-contents">
      <div class="contents-container clearfix">
        <div class="layout-column-main">
          <div class="order-main">
            <div class="order-menus">
                <span data-is="raw" content="人気">
                  <%= link_to "人気", popular_category_path(@category) %>
                </span>
                <span data-is="raw" content="新着">
                  <%= link_to '新着', newest_category_path(@category) %>
                </span>
                <span data-is="raw" content="昔の投稿">
                  <%= link_to '昔の投稿', oldest_category_path(@category) %>
                </span>
            </div>
          </div>
          <div class="story-list clearfix">
            <%= render partial: "application/story-box", collection: @storys, as:"story" %>
          </div>
          <div data-is="category__paginate">
            <%= paginate(@storys) %>
          </div>
          <%= render 'layouts/recommend' %>
        </div>
          <div class="all-count">
            全 <span> 000 </span> ストーリー
          </div>
          <%= render 'latest/rightside' %>
        </div>
    </div>
    <%= render 'application/footer' %>
  </div>
</div>

app/views/latest/index.html.erb
<%= render 'application/titlebar' %>
<div class="container-latest">
  <%= render 'application/toolbar' %>
  <div class="main">
    <div class="contents">
      <div class="contents-container clearfix">
        <div class="layout-column-main">
          <h1 class="h1-global">
            <i class="fa fa-flash"></i>
            新着のストーリー</h1>
          <div class="story-list clearfix">
            <%= render partial: "application/story-box", collection: @storys, as:"story" %>
          </div>
          <div data-is="category__paginate"><%= paginate(@storys) %></div>
          <%= render 'layouts/recommend' %>
        </div>
        <%= render 'latest/rightside' %>
      </div>
    </div>
    <%= render 'application/footer' %>
  </div>
</div>

app/views/likes/_like.html.erb
<div class="like-link" id="like-link-<%= story.id %>">
  <% if current_user.likes.find_by(story_id: story.id) %>
    <%= link_to like_path(story.id), method: :delete, remote: true do %>
        <div class = "iine__button">読んで良かった❤️<%= story.likes.count %></div>
    <% end %>
  <% else %>
    <%= link_to likes_path(story.id), method: :post, remote: true do %>
        <div class = "iine__button">読んで良かった♡️<%= story.likes.count %></div>
    <% end %>
  <% end %>
</div>

app/views/likes/create.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like", story: @story  )) %>');

app/views/storys/_storys.html.erb
<%= render 'likes/like', story: story %>

app/views/storys/index.html.erb
<%= render 'application/titlebar'%>
<div class="container">
  <%= render 'application/toolbar'%>
  <div class="main">
    <div can_delivery_other="true" data-is="story-id-top" is_me="true">
      <div class="pankuzu">
        <div class="container">
          <a class="to-top" href="/">トップページ</a>    <!-- まだ実装中の機能であるのでaタグのままにしています-->
          <span>></span>
          <a class="category" href="">カテゴリ名</a>     <!-- まだ実装中の機能であるのでaタグのままにしています-->
        </div>
      </div>
      <div class="global-box">
        <div class="container">
          <div class="wall">
            <% @storys.each do |story| %>
              <%= link_to '削除', story_path(story), method: :delete, class: 'story__delete' %>
              <%= link_to '編集', edit_story_path(story), class: 'story__edit' %>
          </div>
          <a class="read" href="/">       <!-- まだ実装中の機能であるのでaタグのままにしています-->
            <div class="inner">
              <i class="fa fa-arrow-right"></i>
              続きを読む
            </div>
          </a>
          <div class="body">
            <p class="reading_time">1 min read</p>
            <a class="linked" href="/story/story_id">       <!-- まだ実装中の機能であるのでaタグのままにしています-->
              <h2 class="title" data-is="print" labal=""><%= story.title %></h2>
              <div class="discription" style="padding: 0; margin-top: 10px; height: 40px; font-size: 14px; color: #807975;">
                <%= story.text %>
              </div>
            <% end %>
            </a>
            <div class="tags">
              <div class="announce">
                <i class="fa fa-plus"></i>
                <span>読者の方もタグを追加できるな機能を実装中です！</span>
              </div>
            </div>
            <div class="next_prev_stories clearfix">
              <div class="prev">
                <span>
                  <i class="fa fa-arrow-left"></i>
                  前編へ
                </span>
              </div>
              <div class="next"></div>
              <div class="next">
                <a href="/">             <!-- まだ実装中の機能であるのでaタグのままにしています-->
                  続編を書く
                  <i class="fa fa-arrow-pencil"></i>
                </a>
              </div>
            </div>
            <%= render '/storys/social'%>
          </div>
        </div>
      </div>
    </div>
    <div class="contents">
      <div class="contents-container clearfix">
        <div class="layout-column-main">
          <div class="story-add-engagement">
            <h3 class="h3-global">みんなの読んで良かった！</h3>
            <div data-is="story-id-bookmark-form" >
              <div class = "inner" >
               <div class="icon"></div>
               <textarea>読んで良かったにコメントを添える...</textarea>
               <%= render partial: 'storys', collection: @storys, as: :story %>
              </div>
                <i class = "fa fa-star"> </i>
           </div>
          </div>
        </div>
        <div class="layout-column-right"></div>
        <%= render 'layouts/recommend'%>
      </div>
    </div>
    <%= render 'application/footer' %>
  </div>
</div>

app/views/storys/show.html.erb
<div class="topbarwrapper">
  <%= render 'application/titlebar'%>
  <div data-is="categorybar-wrapper">
    <div class="categorybar">
      <div class="category-container">
        <div class="menu">
          <%= link_to(root_path, class: 'category__bg__after top')do %><span data-is="print" label="TOP">TOP</span><% end %>
          <%= link_to(latest_path, class: 'category__bg__after top')do %><span data-is="print" label="新着">新着</span><% end %>
          <%= link_to(legend_path, class: 'category__bg__after legend')do %><span data-is="print" label="殿堂入り">殿堂入り</span><% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <%= render 'application/toolbar'%>
  <div class="main">
    <div can_delivery_other="true" data-is="story-id-top" is_me="true">
      <div class="pankuzu">
        <div class="container">
          <a class="to-top" href="/">トップページ</a><!-- 未実装の機能のため今後リンク先を追加する予定です。-->
          <span></span>
          <a class="category" href="">カテゴリ名</a><!-- 未実装の機能のため今後リンク先を追加する予定です。-->
        </div>
      </div>
      <div class="global-box">
        <div class="container">
          <div class="wall">
            <%= image_tag(@story.category.image)%>
              <% if user_signed_in? && current_user.id == @story.user_id %>
                <%= link_to '編集', edit_story_path(@story), :style => "right: 115px;"%>
                <%= link_to '削除', story_path(@story), method: :delete, :style => "right: 65px;" %>
              <% end %>
          </div>
          <%= link_to(show__detail_path(@story), class: 'read') do %>
            <div class="inner">
              <i class="fa fa-arrow-right"></i>
              続きを読む
            </div>
          <% end %>
          <div class="body">
            <p class="reading_time">1 min read</p>
            <a class="linked" href="/story/story_id"><!-- 未実装の機能のため今後リンク先を追加する予定です。-->
              <h2 class="title" data-is="print" labal=""><%= @story.title %></h2>
              <div class="discription" style="padding: 0; margin-top: 10px; height: 40px; font-size: 14px; color: #807975;">
                <%= @story.text %>
              </div>
            </a>
            <div class="tags">
              <div class="announce">
                <i class="fa fa-plus"></i>
                 <span>読者の方もタグを追加できるな機能を実装中です！</span>
              </div>
            </div>
            <div class="next_prev_stories clearfix">
              <div class="next">
                <% if user_signed_in? && current_user.id == @story.user_id %> 
                  <%= link_to "続編を書く", new_story_path(@story) %>
                  <i class="fa fa-arrow-pencil"></i>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="contents">
      <div class="contents-container clearfix">
        <div class="layout-column-main">
          <div class="story-add-engagement">
            <%= render partial: 'likes/like', locals: {story: @story} %>
            <h3 class="h3-global">みんなの読んで良かった！</h3>
            <div data-is="story-id-bookmark-form" >
              <div class = "inner" >
               <div class="icon"></div>
              </div>
                <div class="comments">
                  <%= form_for [@story, @comment] do |f| %>
                    <%= f.text_field :text, placeholder: "コメントを書いてね！" %>
                    <%= f.submit "送信"%>
                  <% end %>
                <h3>＜コメント一覧＞</h3>
                 <%= render partial: 'comments', collection: @comments %>
                </div>
            </div>
          </div>
        </div>
        <div class="layout-column-right"></div>
        <%= render 'layouts/recommend'%>
      </div>
    </div>
    <%= render 'application/footer' %>
  </div>
</div>

app/views/storys/show2.html.erb
<%= render 'application/titlebar' %>
<div class="container-latest">
  <%= render 'application/toolbar' %>
  <div class="main">
    <div class="main-contents">
      <div class="contents-container clearfix">
        <div class="layout-column-main">
          <div id="breadcrumbs">
             <%= link_to "TOP", root_path, class: "breadcrumbs__top" %> >
             <%= link_to "#{@story.category.name}", category_path(@story.category_id), class: "breadcrumbs__name" %> >
             <%= @story.title %>
          </div>
            <div class="story-add-engagement">
              <img src="<%= @story.category.image %>" alt="<%= @story.category.name %>">
              <h2><%= @story.title %></h2>
              <div class = "writer__name" >著者 : <%=@story.user.name %></div><br>
              <%= @story.text %>
            </div>
          <%= render 'layouts/recommend' %>
        </div>
          <%= render 'latest/rightside' %>
      </div>
    </div>
    <%= render 'application/footer' %>
  </div>
</div>

app/views/storys/show__detail.html.erb
<%= render 'application/titlebar' %>
<div class="container-latest">
  <%= render 'application/toolbar' %>
  <div class="main">
    <div class="main-contents">
      <div class="contents-container clearfix">
        <div class="layout-column-main">
          <div id="breadcrumbs">
            <%= link_to "TOP", root_path, class: "breadcrumbs__top" %> >
            <%= link_to "#{@story.category.name}", category_path(@story.category_id), class: "breadcrumbs__name" %> >
            <%= @story.title %>
          </div>
            <div class="story-add-engagement">
              <%= image_tag(@story.category.image)%>
              <h2><%= @story.title %></h2>
              <div class = "writer__name" >著者 : <%= @story.user.name %></div><br>
              <%= @story.text %>
            </div>
          <%= render 'layouts/recommend' %>
        </div>
          <%= render 'latest/rightside' %>
      </div>
    </div>
    <%= render 'application/footer' %>
  </div>
</div>